[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Orise_Twin_Rotor"
version = "0.0.1"
authors = [
  { name="Orise"},
]
description = "Orise Twin Rotor Library"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Orise-Innovations/Twin_Rotor_Research_Platform"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]